# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory TestResults
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.5
      with:
       reports: TestResults/**/coverage.cobertura.xml
       targetdir: CoverageResults
       reporttypes: Html;lcov
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
